id: I203D845B
legacy_id: P002911
ocr_import_info:
  bdrc_scan_id: W29674
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T19:33:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:16:22.232021+00:00'
last_modified: 2022-09-02 22:16:39.153268
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29674
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29674
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགེ་སྦྱོང་གི་འབྲས་བུ་བཞིའི་སྐོར་ལ་དཔྱད་པ་བློ་ལྡན་ཡིད་ཀྱི་འཁྲི་ཤིང་།
  author: སྤྲུལ་སྐུ་དགེ་འདུན་རབ་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.9509950855683991
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I5561:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5561
      total_pages: 37
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5561.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9509950855683991
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
