id: I203D845B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:33:33+00:00'
last_modified: '2022-06-07T16:08:04.725685+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29674
  title: དགེ་སྦྱོང་གི་འབྲས་བུ་བཞིའི་སྐོར་ལ་དཔྱད་པ་བློ་ལྡན་ཡིད་ཀྱི་འཁྲི་ཤིང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    943F:
      image_group_id: I5561
      title: ''
      total_pages: 37
      order: 1
      base_file: 943F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
